spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: spring
    password: spring
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  message:
    basename: i18n/message
    encoding: UTF-8
    default-locale: en
  #flyway
  # duong dan toi thu muc chua cac script flyway
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baseline-on-migrate: true
    baseline-version: 0
api:
  prefix: api/v1
logging:
  level:
    root: info
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: 8pwwqGd9QvaB9idTkGvwqI8nEpu5ho/qHI/wRy5yUrM=

logging.level.org.springframework.security: DEBUG




